// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDiZ-7i1wF1i8QJ1rrpBuM1qdtbS2oOZw',
    appId: '1:1033009541201:web:05a7414eda4f7bdf44c870',
    messagingSenderId: '1033009541201',
    projectId: 'task-points-76836',
    authDomain: 'task-points-76836.firebaseapp.com',
    databaseURL: 'https://task-points-76836-default-rtdb.firebaseio.com',
    storageBucket: 'task-points-76836.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTxoC2RpR3jVg9SkTwHpFLh4N7aa04Kdw',
    appId: '1:1033009541201:android:18738e26eb0e965544c870',
    messagingSenderId: '1033009541201',
    projectId: 'task-points-76836',
    databaseURL: 'https://task-points-76836-default-rtdb.firebaseio.com',
    storageBucket: 'task-points-76836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdQyLTVfSmU8GdoVBRnKIWne8N7HXXRE',
    appId: '1:1033009541201:ios:3f8329cf6e230c5144c870',
    messagingSenderId: '1033009541201',
    projectId: 'task-points-76836',
    databaseURL: 'https://task-points-76836-default-rtdb.firebaseio.com',
    storageBucket: 'task-points-76836.appspot.com',
    iosBundleId: 'br.gabriethales.dev.taskPoints',
  );
}
